version: '3'
services:
  dbbachinski:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: 'dacs2022'
      MYSQL_USER: 'admin'
      MYSQL_PASSWARD: 'root'
      MYSQL_ROOT_PASSWARD: 'root'
    ports:
      -'3312:3306'  
    expose:
      - '3012'  
  webdacsbachinski:
    image: bachinskidacs2022:latest
    depends_on: 
      - "dbbachinski"
    ports:
      - "8087:8081"
    environment:
      - DB_HOST=dbbachinski:3312
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=dacs2022
      - SPRING_PROFILES_ACTIVE=prod